# Docker compose para la creación de manylinux wheels en linux 32 
# bits y 64 bits
version: '3'

services:
  #Creando el container para linux 32 bits
  linux32:
    container_name: linux32
    #Especificamos la imagen a utilizar
    image: quay.io/pypa/manylinux1_i686
    #Link para que el script se pueda utlizar desde dentro del contenedor
    volumes:
      -./scripts/wheel.sh:./scripts/wheel.sh
    #Script para la creación de las wheels
    command: bash scripts/wheel.sh Proyecto2017UGR

  
  #Mismo proceso para linux 64 bits
  linux64:
    container_name: linux64
    image: quay.io/pypa/manylinux1_x86_64
    volumes:
      -./scripts/wheel.sh:./scripts/wheel.sh
    command: bash scripts/wheel.sh Proyecto2017UGR